### ISSUE TITLE
Thermal Expansion Arboreal Extractor GUI

### ISSUE THREAD

**Issue by mcdodge34** [F32Organization/Faithful32-1.12.2#10]
I've noticed the Thermal Expansion Arboreal Extractor GUI is incorrect, there's a slot to insert some fertilizer and we don't see it, I would say that a few devices could have the same problem since they aren't the in the machines tab but in the devices tab of the GUI section, and they have weird names, pretty sure arboreal extractor is the tapper.png there...

**Comment by StefanTT** [comment]
@Intipablo I think this issue is something for you

**Comment by mcdodge34** [comment]
I'm sorry, don't have the required skills for that nor the patience needed to do something that would be acceptable, just there to help out track stuff that aren't done if this is of any help, would love to contribute more, but I don't have the required skills like I say.

**Comment by StefanTT** [comment]
no problem @mcdodge34

**Comment by anders0nmat** [comment]
Im currently busy but in a few weeks i will try to fix it.

**Comment by mcdodge34** [comment]
Great, I respect that real life is more important than game modding, after all you do this for free for all to enjoy, take the time you need.

**Comment by Intipablo** [comment]
I'd just like to add. If you see any textures in your game that aren't supported. Please tell me/us! Make an issue on here and I will start working on it (as long as it's within my capabilities).
