### ISSUE TITLE
Broken texture pack after updated f32 1.12.2

### ISSUE THREAD

**Issue by jenci8888** [F32Organization/Faithful32-1.12.2#105]
I'm not sure where I start here (to make issue), anyway I tried to use the latest F32 1.12.2 but seems broken fonts and other textures, the old texturepack seems fine.

Before
![image](https://user-images.githubusercontent.com/40495799/58275638-d5ad1500-7d95-11e9-91b6-f98ee877f9de.png)

After (random other break texture things) I tested on FTB Continuum, Direwolf20 and this.
![image](https://user-images.githubusercontent.com/40495799/58275618-c7f78f80-7d95-11e9-92ff-c9e5b3362f1a.png)

**Comment by Bernasss12** [comment]
Could you please explain a little better how you've come across this issue?

**Comment by jenci8888** [comment]
Uhhh.... (no idea I wanted to check if there's archive updates in f32.me but I can't find last time checked f32.me site)

I was busy at school, I had no time to play and not updating texture pack, so please would you link me to see archive f32 texture packs? (and download too?)
Unfortunately, I have one got working f32 about size 26KB and one isn't working on the latest is 34KB
And I'll do test all f32 updates if I see any regression and I'll reply you in this here, later.

**Comment by Bernasss12** [comment]
I don't think this is necessarily the texturepack's fault, if I remember correctly the custom main menu resources are stored in a different folder called resources. I may be wrong but the resourcepack shouldn't affect/replace the textures inside that folder.
Anyways I'm installing the pack myself to see if I can replicate the problem.

**Comment by StefanTT** [comment]
Did you try if restarting Minecraft helps? Disorted textures is something that I see frequently when switching texture packs. There is nothing that we can do about it.

**Comment by jenci8888** [comment]
Thank you for answer! I cannot to solve problem when restarting Minecraft nor reinstall modpack anything. (including profile repair.)
Here's my proof recording:
https://i.imgur.com/8jU1iZm.gifv

**Comment by StefanTT** [comment]
Hmm ... the problem is that F32 is simply a texture pack and I am pretty confident that the background of your game's start screen is not in this pack. At the moment it looks like you are the only person who has this problem and for us it simply works. Granted we seem to play another pack (Enigmatica 2 expert in my case).

I have no idea how I could help you here, unforunately :-/

**Comment by jenci8888** [comment]
I was testing if it works, after dragging folder (these are added folder which old didn't) from the latest texture pack to old texture pack (Now about 35KB) and now it works on "f32.zip (2)"...
![image](https://user-images.githubusercontent.com/40495799/58307579-69ff9200-7dff-11e9-93d7-4eaea73412d8.png)

**Comment by StefanTT** [comment]
The unmodded minecraft textures were removed ~ 8 months ago, see https://github.com/F32Organization/Faithful32-1.12.2/blob/master/README.md
