### ISSUE TITLE
Texture issue 

### ISSUE THREAD

**Issue by Dexy2811** [F32Organization/Faithful32-1.12.2#106]
Fluix cable is pink/purple is it suppose to be like that?
and the connection from a [fluix cable to a ME interface](https://imgur.com/a/NljMdvC) texture is broken

**Comment by Dexy2811** [comment]
![2019-06-16 (3)](https://user-images.githubusercontent.com/38790678/59568546-581ab300-907c-11e9-973f-bd01ef4e727e.png)
Silk grass pixel missing

**Comment by StefanTT** [comment]
Sigh, different things in one issue is not that great.

The silk grass is a duplicate of issue #102

The ME cable are missing in the texture pack. I doubt that it is our problem. Did you verify if it happens without F32 too ?

**Comment by Dexy2811** [comment]
yeah this doesn't happen without a texturepack

**Comment by Dexy2811** [comment]
Is the fluix cable supposed to be pink/purple?

**Comment by agarian-2** [comment]
Silk grass issue should be fixed by my pull request.

**Comment by Dexy2811** [comment]
okay will check out

**Comment by StefanTT** [comment]
@Dexy2811 is it fixed now?

**Comment by Dexy2811** [comment]
Yes its fixed I havnt seen this issue again

**Comment by StefanTT** [comment]
Ok thank you!
