### ISSUE TITLE
Some Suggestions

### ISSUE THREAD

**Issue by Intipablo** [F32Organization/Faithful32-1.12.2#13]
**Modlist in README:**

I think we should put a mod list of all the mod compatibility in the readme. So people can easily come and see what mods we have finished, are working on, and haven't done yet.

We could have a table like CyanideX does at his unity GitHub here: https://github.com/CyanideX/Unity

So we have each mod. The person/artist working on it, and the progress.

------------------------------------------------------------------------------------------------

**Discord:**

I think it would be a great idea to have a discord server or a place outside of Github where we can message each other and discuss our progress with texturing.

I'd be willing to set up a server if anyone would like.

**Comment by anders0nmat** [comment]
The question is, who would update the table and how do you mesaure the progress? I agree that there is a need to have a mod checklist, so someone can easily look what he/she can work on but for the contributors its additional work which is annoying.

Discord server would be practical but i personally would write rarely bc nearly everytime i think my english skills are poor even if i know that everyting is fine with it. But if you would do so, go for it.

**Comment by Intipablo** [comment]
I agree with you on the first part. I guess just a list of mods we are working on, ones that are complete, and ones that are planned would be good. At least so we don't have to constantly update the progress/percentage part of things.


I was thinking a Discord server would be more to review anyone's textures if they are not sure about them or about to submit them in a PR. I didn't really plan for there to be much conversing either as I'm sure we all have busy lives.

And just a place for us to talk about anything, suggestions, etc. So we don't have to make issues just to have a normal conversation.

**Comment by StefanTT** [comment]
To be honest I doubt that the mod list will be very much up to date but it's fine for me if you want to try it.

According to the Discord channel: I have 3-4 different chat protocols that are luckily all handled by Pidgin. Discord is not, and I do not want to start another chat client just for it. But I am not everybody, so please feel free to create one.

**Comment by Intipablo** [comment]
Yes I understand. This can be closed then once anders0nmat's PR is accepted. We can just chat here for now.
