### ISSUE TITLE
'Tranparent' Factory Block texture not actually transparent

### ISSUE THREAD

**Issue by Endur1el** [F32Organization/Faithful32-1.12.2#139]
We were building a base using the factory blocks from Chisel and discovered that one of the textures intended to be transparent 
![image](https://user-images.githubusercontent.com/50383024/68851438-41819200-06d6-11ea-8b46-7b9801636c8d.png)
was actually not
![image](https://user-images.githubusercontent.com/50383024/68851474-4d6d5400-06d6-11ea-8ab4-5f56a3f462c5.png)
As you can see its the rusty scaffold texture from chisel factory blocks.

**Comment by anders0nmat** [comment]
Fixed. Texture now is transparent
