### ISSUE TITLE
Transparent chisel blocks

### ISSUE THREAD

**Issue by Jeppeskovsgaard** [F32Organization/Faithful32-1.12.2#143]
Many blocks from the mod Chisel are missing textures. They are completely transparent. This is not just cobblestone but other blocks as well. 

I'm using the latest version of F32 1.12 alongside the vanilla/standard textures with the modpack FTB Revelation 1.12. No shaders or anything else - just FTB Revelation.

You can see a screenshot here: https://imgur.com/a/255WwzB

With F32 disabled I can see all the blocks.

I can see that the textures are in this repository, but there's some kind of bug that renders them transparent.

**Comment by Amp1810** [comment]
I found with version 1.12.2-0.2.1.35 that I was using and is the same in FTB Revelation and I was having this issue with, that if you go through the Chisel asset folder and through the blocks and remove all of the .mcmeta files that will solve the issue with the transparent blocks. Alternatively the newer versions of Chisel seems to have this fixed without any need of editing the resource pack

**Comment by Jeppeskovsgaard** [comment]
> I found with Chisel version 1.12.2-0.2.1.35 that I was using and is the same in FTB Revelation and I was having this issue with, that if you go through the Chisel asset folder and through the blocks and remove all of the .mcmeta files that will solve the issue with the transparent blocks. Alternatively the newer versions of Chisel seems to have this fixed without any need of editing the resource pack

Interesting - will try that. What are those meta files used for? Can they safely be deleted?

**Comment by Amp1810** [comment]
They tell which texture and where to find them however seems to be safe to remove them, that's how I fixed that issue. I was also referencing Sphax Texture pack for chisel as well and in theirs they do not include the meta files in it either and theirs renders without issue. So with my testing so far at the very least everything seems to be rendering properly and with right textures without the meta files.

**Comment by Jeppeskovsgaard** [comment]
I can confirm that deleting all .mcmeta files in the resource pack indeed solves the display issue. Thanks @Amp1810

**Comment by anders0nmat** [comment]
Probably outdated. Chisel versions >= 1.0.1.44 should work fine
