### ISSUE TITLE
Natura Berry Bushes Bugged Textures

### ISSUE THREAD

**Issue by Misl3d** [F32Organization/Faithful32-1.12.2#147]
When using Fast graphic settings, berry bushes aren't transparent/are filled incorrectly
[![Screenshot from Gyazo](https://gyazo.com/7632a68be440eba1a283cade21f5a19a/raw)](https://gyazo.com/7632a68be440eba1a283cade21f5a19a)

**Comment by StefanTT** [comment]
Fast does rendering shortcuts. Some mods then have flickering surfaces for example. I highly doubt that this is an issues that can be handled on our side.
