### ISSUE TITLE
After applying modded version the sound of the game is gone

### ISSUE THREAD

**Issue by lasiecz** [F32Organization/Faithful32-1.12.2#164]
Hey guys,

after I applied the ResourcePack my sound from the whole game is gone.

What is wrong?

Thank you for your help.

Lenka

**Comment by lasiecz** [comment]
PS: tried the F3+T to reload resource pack and it didn't worked, sound was OK before the RS

**Comment by StefanTT** [comment]
Last time I looked our pack does not include sounds. There is absolutely no reason that this mod pack is to blame for missing sound. However, good luck finding the issue!

**Comment by lasiecz** [comment]
It is OK now I was just soooooo dumb :D I just had to restart the whole game so I am sorry ♥
