### ISSUE TITLE
mcmeta files

### ISSUE THREAD

**Issue by anders0nmat** [F32Organization/Faithful32-1.12.2#172]
Hey, i just had to solve an issue regarding outdated mcmeta files. Just the files, not the textures.

I wondered whether we even need them or not bc MC just grabs the topmost file to load, so when we dont provide said mcmeta (or ctx) file, it will just grab the one included in the mod and from there on it will grab our textures. This way, we dont have to worry about outdating mcmeta files (like with chisel mod)
I'd go trough our tp and delete all unnecessary non-texture files.
Is there an error in my thinking? Why do we even included them in the first place?

**Comment by StefanTT** [comment]
It might cause other issues when I am not mistaken. I think we had issues in the past when these files were not added to the pack. But feel free to remove those that had issues as a test.

**Comment by Ethryan** [comment]
Sometimes without the mcmeta files, the texure fails to load.

It seems the texture file and the mcmeta file has to be loaded close together to avoid the porple block/item texture error.

**Comment by anders0nmat** [comment]
Atleast for chisel it seems to work. 
https://github.com/F32Organization/Faithful32-1.12.2/issues/143#issuecomment-564327127
"I was also referencing Sphax Texture pack for chisel as well and in theirs they do not include the meta files in it either and theirs renders without issue"

**Comment by StefanTT** [comment]
If it works for chisel then you can remove them. Simply commiting the updated files might be the safer bet, however.
