### ISSUE TITLE
[Mod Support] Tinkers' Construct 2 Help Wanted 

### ISSUE THREAD

**Issue by smokeXTR** [F32Organization/Faithful32-1.12.2#182]
Tinkers' Construct 2

https://www.curseforge.com/minecraft/mc-mods/tinkers-construct

tool parts looks fine but when you forge them the item becomes white so all my tinkers items are white and i cant see them on my hand anymore

**Comment by anders0nmat** [comment]
I am sorry to hear about that, however i am not able to reproduce the error. In my test-world our texturepack does not turn the tool parts white, everything seems correct. Maybe another mod is causing the inconvenience? I have a similar issue in Project Ozone 3 where some tool materials are plain white (even with Vanilla textures).
