### ISSUE TITLE
[Mod Support] **More Furnaces** (broken in MC1.12.2_v1.1.0)

### ISSUE THREAD

**Issue by draeath** [F32Organization/Faithful32-1.12.2#190]
**Mod Name**
More Furnaces

**Link to the mod (ideally Curseforge)**
https://www.curseforge.com/minecraft/mc-mods/more-furnaces

Support for this was added in #176 and this worked in MC1.12.2_v1.0.6, however the GUI is mangled in MC1.12.2_v1.1.0 (all slots are offset _significantly_ from the visual slots along both X and Y). This was noticed in Omnifactory, which uses the most recent 1.12.2 version of More Furnaces (MoreFurnaces-1.12.2-1.10.6.jar and cxlibrary-1.12.1-1.6.1.jar)

**Comment by draeath** [comment]
Related to e44afbb1825222b0f013f4290a2ddebb420b6c29 possibly

**Comment by Telokis** [comment]
I wonder if this issue come from this resource pack. Even without it, the GUI for the furnaces seem to be a bit misbehaving. I have seen it disappear for no reason. (Though I haven't seen the offset issue without the resource pack)

**Comment by Telokis** [comment]
Removing the `.json` files from the directoy seems to have solved the issue for me.
