### ISSUE TITLE
AE2 Cables have weird texture

### ISSUE THREAD

**Issue by DJ411** [F32Organization/Faithful32-1.12.2#20]
After noticing the Glacial Precipitator has the wrong GUI with the older pack i had, i looked for a newer pack. Downloaded this one and it worked. Sadly AE2 cables didn't.

https://gyazo.com/13c77a7f2baeb804dc5c781640aee668

**Comment by StefanTT** [comment]
Did you test if restarting Minecraft fixes your problem?

**Comment by DJ411** [comment]
Looks like restarting worked. Weird never had that issue, plus with a fix that easy. Sorry for wasting time, maybe others have this issue to and can be a guide to help them.

**Comment by StefanTT** [comment]
No problem. I was quite sure, it happens sometimes when changing texturepack, also with other packs.
