### ISSUE TITLE
issue with a texture

### ISSUE THREAD

**Issue by SteamDoge9000** [F32Organization/Faithful32-1.12.2#214]
**Mod Name**
Thaumcraft

I am aware that this is not what this should be reported

I would like to report an issue with the texture known as Brain Box and it not being shown correctly for some reason

![image](https://user-images.githubusercontent.com/38770780/99604138-d34f6980-29d2-11eb-9333-4dc0eaacd56e.png)

if you can correct this this would be appreciated

**Comment by SteamDoge9000** [comment]
I found the issue, I think the texture was never fully completed

![brain_box](https://user-images.githubusercontent.com/38770780/99605546-e44daa00-29d5-11eb-9f73-811e948a958f.png)
![brain_box  original](https://user-images.githubusercontent.com/38770780/99605549-e44daa00-29d5-11eb-93a1-099c6de3c2a8.png)

**Comment by SteamDoge9000** [comment]
I asked a friend and they managed to do a hackjob in between the textures I found in the mod and in the texture pack

This is what he gave me and it worked
![brain_box](https://user-images.githubusercontent.com/38770780/99608496-00ece080-29dc-11eb-8bc4-05650a932bc5.png)
![image](https://user-images.githubusercontent.com/38770780/99608504-05b19480-29dc-11eb-98ba-9e236caf4837.png)

**Comment by StefanTT** [comment]
It probably broke due to a change in Thaumcraft. Something like this happens every now and then.

It would be easier if mod authors would use a new name if the texture of something changes drastically.
But they are not aware of the problem that they cause, or they simply do not care. I think we simply must
live with it.

**Comment by StefanTT** [comment]
Fixed by pull request #215
