### ISSUE TITLE
[BUG] ProjectRed Illumnation's Inverted Lamps are showing icons on it

### ISSUE THREAD

**Issue by DrumSlayers** [F32Organization/Faithful32-1.12.2#229]
Hello,
I have both latest version of Faithful & Faithful32 modded
Inverted Lamps of the ProjectRed Illuminations mod are showing icon on it, like you can see on the screenshot below
![image](https://user-images.githubusercontent.com/4050278/114319916-ccf19380-9b13-11eb-950a-85c7ce0a4e79.png)
![2021-04-11_20 57 39](https://user-images.githubusercontent.com/4050278/114319943-e692db00-9b13-11eb-845f-84b629a2053e.png)
![2021-04-11_20 57 45](https://user-images.githubusercontent.com/4050278/114319944-e7c40800-9b13-11eb-9edb-ab1d5398ed5d.png)

The issue isn't here without the F32 pack

Can you look at it? Thanks :)

**Comment by Evolution0** [comment]
Weird, the Project Red textures were updated 3 years ago and not a peep about an issue like this in all that time?

Now hear me out, those icons don't look like anything from Project Red, and after digging through the textures I can't find them at all.

However, they *do* look like icons I have seen I think in Journeymap for making waypoints. I'm not sure if its an addon for journeymap that adds the icons or if it was just something included in a previous version (or enabled via config)

Its likely another mod entirely is broken or something else is causing the texture to be overlaid onto the lamps.

Try disabling Journeymap, playing with Optifine settings (or disable it) if you are using it, or disabling shaders if using those.

I have had optifine and shaders do some funky stuff.

**Comment by DrumSlayers** [comment]
> e

Thanks for the reply. 
I tried removing my shader, and it does fix the thing. I'm looking around why it's doing this (shader + stock texture = no problem, that's weird)

I think you are right about JourneyMap. I found a pic on the root of game folder called "waypoints_0.png" and it's exactly this 
![waypoints_0](https://user-images.githubusercontent.com/4050278/114327394-2ae4a200-9b39-11eb-8e0c-d2c13d3a78a1.png)
I will try tomorrow to see why it's doing this, maybe trying to remove the file.

**Comment by Evolution0** [comment]
If you have waypoints visible outside of the map (in overworld) try disabling that, I have had it break many times with shaders.

**Comment by Salamance73** [comment]
I hate to open closed issues but im having a similar issue but its the entire atlas on the blocks. im guessing its still shaders related but im not too sure. im using both resource packs and trilitons shaders.
![image](https://user-images.githubusercontent.com/26430914/133955870-636494d6-4350-42e8-b811-2439599966cb.png)

**Comment by Evolution0** [comment]
> I hate to open closed issues but im having a similar issue but its the entire atlas on the blocks. im guessing its still shaders related but im not too sure. im using both resource packs and trilitons shaders.
> ![image](https://user-images.githubusercontent.com/26430914/133955870-636494d6-4350-42e8-b811-2439599966cb.png)

Any mods or just the texture pack and that shader?

**Comment by leodesa** [comment]
Hello, I'm having the same problem on a Sky Factory 4 server modified with Project Red and every time I activate the shaders it bothers me. Do you already know any solution?

**Comment by GalaxJann** [comment]
I also have this issue in 1.12.2 with Shader. The Lamps will show the Waypoint-Icon from JourneyMap. When I disable the Waypoint Beacons from JourneyMap, the Icon on the Lamp disappears but then a new icon comes on the Lamp. Very weird.
