### ISSUE TITLE
Fluxducts are all wacky

### ISSUE THREAD

**Issue by Zjcompt** [F32Organization/Faithful32-1.12.2#25]
For some reason my fluxducts all appear very weird, and sometimes they are completely invisible!

Yes I have restarted the game already. I am on FTB Revelations + Optifine.

![image](https://user-images.githubusercontent.com/9084300/37876424-3ee3efc8-301a-11e8-9b7f-fe9a5276d8f1.png)

**Comment by StefanTT** [comment]
Please see issue #20

**Comment by Zjcompt** [comment]
Yea, I have restarted about 3-4 times now. Everything else looks great. Just the thermal dynamics ducts.

**Comment by Intipablo** [comment]
We don't actually have textures for Thermal Dynamics do we? Or at least I can't find any.

**Comment by StefanTT** [comment]
I cannot find any either.
Besides that it works for me and I also use Optifine.

**Comment by StefanTT** [comment]
@Zjcompt: any news about your problems?
