### ISSUE TITLE
Problems with PAE2 Fluid Interface

### ISSUE THREAD

**Issue by IntegerLimit** [F32Organization/Faithful32-1.12.2#255]
Incorrectly displays a 6 slot interface instead of a 9 slot. This commit: https://github.com/PrototypeTrousers/Applied-Energistics-2/commit/de324aad91613234b0a35847b7effa7dfac9f087 where they renamed the texture for 9-slot interfaces means that it is now possible to create a new texture for PAE2's 9 slot fluid interfaces.

**Comment by marisathewitch** [comment]
![interfacefluid](https://user-images.githubusercontent.com/5376817/203005977-3286bdf2-4bfb-44d5-a977-9e540d16ad07.png)
Here temporary solution

**Comment by IntegerLimit** [comment]
How can I use that?

**Comment by marisathewitch** [comment]
Sure.

**Comment by IntegerLimit** [comment]
I mean, do I just save the file as interfacefluidextendedlife.png?

**Comment by IntegerLimit** [comment]
But they renamed the PAE2 9-slot interface to a different texture? (As per my previous comment)

**Comment by marisathewitch** [comment]
Oh, i dont see that update. my bad

**Comment by IntegerLimit** [comment]
Yeah, you should be able to add it to the resource pack, and it will work for new PAE2 versions. At the moment, I believe a replacement of the file is still needed, but just add it for the future, under interfacefluidextendedlife.png.

**Comment by peterhaneve** [comment]
#259 should fix this issue
