### ISSUE TITLE
(suggestion) update the curseforge archive/some mod suggestions

### ISSUE THREAD

**Issue by kuroyure** [F32Organization/Faithful32-1.12.2#31]
Few mods that imo would be interesting to have an 32x version(not a request Just a suggestion)
Ice and fire
Thaumcraft 6
Animania
Jurassicraft
the betweenlands
Embers
Roots classic

**Comment by anders0nmat** [comment]
Thanks for your suggestion.
I can't talk for everybody but i am horrible at creating new textures out of nowhere, Im more the Copy&Paste Guy. Currently we are 4 persons working at this pack in our freetime so dont expect the mods added very fast. 
I would suggest to leave this as an open issue (maybe you @StefanTT can label it as "Suggestion" or something).

**Comment by StefanTT** [comment]
Good idea :-)

**Comment by anders0nmat** [comment]
yesterday i requested a commit where i added all the 1.7 Thaumcraft textures. someone just have to rename them all.

**Comment by StefanTT** [comment]
We are not on Curse.
You can enable watching in github (top/right of the page).

**Comment by kuroyure** [comment]
How can i know a texture are now on the version um following ?

**Comment by anders0nmat** [comment]
Normally we try to keep textures updated. If there is a texture missing in a Mod listed as "Finished" or "In Progress" you can just open an issue or send a PM to the guy who worked on the mod in the past (a bit harder to find out). You can also work on it yourself (please share if you do so).

**Comment by kuroyure** [comment]
btw why you guys are not on curse, it would ease downloads for ppl and get moe ppl to know your work(very good work btw) also an discord server will get you guys direct feedback

**Comment by anders0nmat** [comment]
Im not sure if you read this so i tag you :P @StefanTT 
(Btw is tere a reason my pull request is ignored?)

**Comment by kuroyure** [comment]
I think i accidentaly closed the issue there is any way to re open It ?

**Comment by anders0nmat** [comment]
the more i think about it the more i would love to get feedback about my textures. Often i am not sure if these textures are good enough so a second opinion would be great

**Comment by kuroyure** [comment]
I personaly would give feedback on the ring textures and the sword of the zephyr , but the rings are gone, but the sword i think It gives only 1triangle but the sword have 3

**Comment by StefanTT** [comment]
Sorry @anders0nmat, I happened to be on holiday. Unfortunately it seems that I am currently the only one that is reviewing / merging. Maybe we should have a talk by times about this :-)

**Comment by anders0nmat** [comment]
Oh i didn't want to interrupt your holidays.
I would appreciate the ability to merge changes myself.
Btw kuroyure asked if it would be possible to put our pack on Curse where more people would be able to find it. That would give me the opportunity to get feedback on the quality of my textures, but I am not sure if its ok on the the licence and copyright side of things.

**Comment by StefanTT** [comment]
You did not, it was a short one :-)

**Comment by anders0nmat** [comment]
Is there any other revenue besides the points/rewards program? Because for that one one must seperatly register, so we can just not use that one. 
(Btw should we just switch to german for communication since its just the two of us?)

**Comment by Intipablo** [comment]
Hey, sorry I haven't been making textures lately, hopefully I find some time to make more soon.  I am all for uploading the pack to Curse.

**Comment by garrim** [comment]
Well I'm reading with enthusiasm hoping this great respak makes its way to
Curse.

I'm also keeping an eye open for something I could help out whith. Testing
or similar.

Kindly
Göran (wie kann ein weniger Deutsch)

**Comment by garrim** [comment]
...also it would be nice with version numbering on the downloadable files...

**Comment by anders0nmat** [comment]
So, just to be sure @StefanTT i am part of the F32 Organisation, what changed? Do i have special permissions or something? Oh and btw is there something about curse now since you dont answered my question...
(The whole message sounds way more unkind than it was suoopsed to be...)

**Comment by StefanTT** [comment]
You should be able to merge pull requests now.

**Comment by anders0nmat** [comment]
Sounds good... The question is in how far @xMrVizzy is interested in this idea.
Another Question... Would it be okay if i use this repository for work? I would create Branches to work in and create a pull requests if im finished working. Would be much less stress for me.

**Comment by anders0nmat** [comment]
@StefanTT it works now... i have also access to labeling settings so my question snaps in: 

> Would it be okay if i use this repository for work? I would create Branches to work in and create a pull requests if im finished working. Would be much less stress for me.

**Comment by StefanTT** [comment]
Please do not use this master repository directly. If you screw up things are getting shitty quickly.

**Comment by anders0nmat** [comment]
No working in branches? ok then...

**Comment by StefanTT** [comment]
You can make branches in your own copy of the repository, just not in the F32 master repository.

**Comment by anders0nmat** [comment]
Ok just to be sure: I really mess up with the Fork stuff. So i asked if it would be a problem when i create a Branch on the original F32Organisation/Faithful32-1.12.2 repository, work on my textures and make a Merge request, delete the Branch and create a new one if i want to work again, this way i dont have the problem keeping my fork up to date and there will be no Commits à la #38 where some kind of double commit appears (e.g #32 and #40 Both add the "Thaumcraft 1.7" commit, seems like a behavior appearing through squashing them together).

**Comment by StefanTT** [comment]
There is no difference in workflow between using your own repository and doing it with the master repository. It will not make your life easier but it will endanger the master repository.

**Comment by anders0nmat** [comment]
how do i keep my fork up to date? one idea was commiting the master to my fork resulting in more commits. Next idea: commiting to a branch in my fork and then squash commit it resulting in tons of "xx commits ahead" in the two branches and also the the repositories. Next idea: Creating a fork, do SOME work and merge, delete fork and so on. Would work just like the branch system i want to do with the difference, that i have to redownload all data again and also weird errors because of "uncommited changes". If you figured out a way to work with forks just like i want to since months, please tell me, i guarantee i oversee a button or something but as i said i oversee it.

**Comment by xMrVizzy** [comment]
For merging modded version this good idea, cause i curently can't contribute that version myself...

**Comment by anders0nmat** [comment]
@StefanTT well, one difference in workflow is 'how do i keep my fork up to date?' another one are commits à la #26 . Github is not made for texture pack work and forks are not made to do massive and constant changes. Could you be mre specific in how this would endanger the master repository? Is it because i could make changes pretty close to the original repo? I dont want to annoy you with that topic since you already said no so if you dont want to discuss that issue anymore please tell me so.

@xMrVizzy so i see that as an okay from your side. I would appreciate to discuss about details (maybe in a new issue, maybe on Discord or something).

**Comment by anders0nmat** [comment]
i think this can be closed now

**Comment by xMrVizzy** [comment]
@anders0nmat you can contact with me in Discord
