### ISSUE TITLE
Private talk with @Intipablo

### ISSUE THREAD

**Issue by anders0nmat** [F32Organization/Faithful32-1.12.2#35]
@Intipablo 
Hey, since there is no way (at least no way i found) to communicate directly i will ask here:
How did you do your fork stuff? In your last pull request is just one commit and not the mess with hundreds of commits. Did you created a new fork? Did you found out a (better) way to fork and work on the project without all the commits flying around in a pull request? How do you keep your Fork up to date?

**Comment by StefanTT** [comment]
I am not @Intipablo but maybe I have some tips. The possibilities that I know of are:
* you can amend your last commit, this will basically expand your commit and not create a new one
* you can squash several commits to one
* you can have several commits  and take them back with git reset and re-commit all as one

Notes:
I usually do the amend variant and only push the commit when I am done with it. The drawback with amending is that you cannot throw away a commit that easily. The reset strategy is a bit tricky.

**Comment by Intipablo** [comment]
I actually created a new fork. Unfortunately I don't think amending commits is possible using GitHub Desktop (which I'm using), neither are the other two. I would like to start using Git but it seems too complicated.

**Comment by Intipablo** [comment]
Update, I've decided to move from Github Desktop to another Git Client. Most likely Sourcetree, it looks nice and simple, and has the ability to amend commits.

**Comment by anders0nmat** [comment]
Im just completely confused with GitHubs behavior. Commiting something, still Commits ahead, Commits behind, meanwhile i just see commits everywhere. Doing Changes on GitHub Desktop, Conflict in merging although i only changed the file. Out of nowhere i merge commits i merged like three times. Updating my fork to get new Content of other commits, boom, another Commit i have to squash that will never disappear. Its a nightmare to me. Im on the point of just leaving the project for a longer time. I really enjoy making textures but merging them into the upstream branch (something new i learned over the last two days, upstream = the original project) cracks me up.
