### ISSUE TITLE
Ender IO misnamed mcmeta files

### ISSUE THREAD

**Issue by GunArm** [F32Organization/Faithful32-1.12.2#49]
The renaming commit from a week ago missed the .mcmeta files.  The result is that these machines show a purple and black texture when the machines are on.

this fixed it for me

Rename assets/enderio/textures/blocks/
alloySmelterFrontOn.png.mcmeta ->  	block_alloy_smelter_front_on.png.mcmeta
stirlingGenFrontOn.png.mcmeta ->          block_stirling_gen_front_on.png.mcmeta
painterFrontOn.png.mcmeta ->            	block_painter_front_on.png.mcmeta

**Comment by anders0nmat** [comment]
ah, right it just occured to me what i forgot to do :D
will fix asap

**Comment by anders0nmat** [comment]
commit #52 fixed it
