### ISSUE TITLE
Buildcraft GUI error

### ISSUE THREAD

**Issue by kellixon** [F32Organization/Faithful32-1.12.2#50]
![2018-08-22_10 36 54](https://user-images.githubusercontent.com/22012731/44455231-312f5400-a606-11e8-807b-2dcf62545063.png)

**Comment by anders0nmat** [comment]
thanks for pointing out, i (or someone else) will fix this GUI and check all other buildcraft related GUIs

**Comment by anders0nmat** [comment]
i fixed that particular texture (#52), there are more of them but i currently dont have time to fix them
