### ISSUE TITLE
Compact machines, miniaturisation field projector

### ISSUE THREAD

**Issue by MyNameBeMrRandom** [F32Organization/Faithful32-1.12.2#53]
Just loaded this pack into my modded world, the miniaturisation field projector has this energy crystal texture on the front of it, is this the packs fault or just a problem with the mod itself?

![2018-08-29_20 42 10](https://user-images.githubusercontent.com/26942107/44811295-396e2d00-abcc-11e8-95cc-6c03c9f7b7e1.png)

**Comment by anders0nmat** [comment]
did you tried restarting the game? I just know some similar issue when switching from Vanilla to F32. Looking at #20.

**Comment by StefanTT** [comment]
Closing the issue: it looks like a problem that is fixed by a reload, and the author of the issue did not answer since 2 weeks.
