### ISSUE TITLE
Uploading to CurseForge

### ISSUE THREAD

**Issue by Intipablo** [F32Organization/Faithful32-1.12.2#56]
So are we uploading to CurseForge or not? There's been a bit of discussion in the discord recently and it seems like many people would like to see the pack be uploaded there. We can turn off the rewards system so that we aren't making any profit off it. Thoughts? @StefanTT ?

**Comment by StefanTT** [comment]
As you are asking me directly: I do not have the time to do it.

**Comment by Intipablo** [comment]
I'm just asking if you have any problems with it. Me or @anders0nmat can handle uploading it.

**Comment by StefanTT** [comment]
It's fine for me as long as there are no revenues collected.

**Comment by Intipablo** [comment]
Sounds good.
