### ISSUE TITLE
Incompatability with Thaumcraft 6

### ISSUE THREAD

**Issue by Yamza** [F32Organization/Faithful32-1.12.2#59]
Please see this issue: https://github.com/Azanor/thaumcraft-beta/issues/1462

**Comment by StefanTT** [comment]
Looks like a custom font that is higher than the standard font.

**Comment by StefanTT** [comment]
Hopefully this issue is fixed by my change. I am usually not playing Thaumcraft, so it would be good if somebody could verify if this is fixed.

**Comment by StefanTT** [comment]
Nobody complained, I am closing this issue now.
