### ISSUE TITLE
[1.12.2v1.0.1] No textures for Botania Mana Pylon or Natura Pylon

### ISSUE THREAD

**Issue by PokeMaserJ** [F32Organization/Faithful32-1.12.2#62]
Quite simply, there is no texture for either of these blocks, so they appear invisible. 
Botania r1.10-356 and forge 14.23.4.2765 if it matters at all.

**Comment by StefanTT** [comment]
The models of botania are all together not in F32, I highly doubt that F32 is the cause for this issue.
I also cannot reproduce the problem, the pylons look ok for me.
