### ISSUE TITLE
JEI textures

### ISSUE THREAD

**Issue by kellixon** [F32Organization/Faithful32-1.12.2#71]
MC 1.12.2. JEI 4.14.4.251.
In the screenshot, on the right is the default JEI, on the left is the Faithful32Mod ResourcePack. Names don't match.
![default](https://user-images.githubusercontent.com/22012731/51085653-7edf6100-174d-11e9-97b2-7054350732c6.jpg)

**Comment by StefanTT** [comment]
yeah ... mod authors tend to rename the assets every now and then.

**Comment by mezz** [comment]
I recently split most of the assets into individual files. 
It should help texture pack support going forward when I add new assets.

**Comment by StefanTT** [comment]
Sure, this makes sense. I will port the new textures in the next couple of days. Many mods have changed the asset names in the last couple of months, I update them when I pass by while playing.

Blocks and items have higher priority, so it might still take some time until the UI stuff is done.

**Comment by anders0nmat** [comment]
i just looked into the latest version in jei and there were just the two textures we cover... weird

**Comment by StefanTT** [comment]
Yes sounds good. I mean if it is only a question of adding stuff then it is fine to have additional files. If the textures contain incompatible changes then it is probably best to stick with the latest release.

**Comment by mezz** [comment]
I’m trying to set things up so changes are done with new files, so the texture packs can support all the versions starting with what you have now and adding files.

**Comment by StefanTT** [comment]
I did not completely verify the new JEI textures but on the other hand I did not find any issues.
Thanks @Ethryan for making them!

Please comment/reopen this issue if there are problems.

**Comment by Ethryan** [comment]
The JEI GUI is missing 2 textures, (favorites books), i will try and create them this weekend.
https://github.com/F32Organization/Faithful32-1.12.2/tree/master/TODO/jei/gui/icons

**Comment by anders0nmat** [comment]
I just checked, JEI is now complete
