### ISSUE TITLE
Update f32.me?

### ISSUE THREAD

**Issue by Intipablo** [F32Organization/Faithful32-1.12.2#8]
Is it possible for someone to update F32.me to the latest versions of all packs (and add 1.12)?

This way more people could access the work we've been doing.

**Comment by StefanTT** [comment]
I do not have access to package creation.
Maybe @smenes can do it.

**Comment by Intipablo** [comment]
If we can not do that, there is the possibility of uploading our own version to curseforge as it is pretty much the most popular site for Minecraft related things right now.

**Comment by mcdodge34** [comment]
There's a version of modded Faithful32 on curseforge, its where I grabbed mine this time before updating and changing and tweaking my version for the 1.12.2 (I change a lot of the base textures that I take from other packs. Maybe there's a possibility to update the one that is already on curseforge then...

**Comment by StefanTT** [comment]
This is not from here, @xMrVizzy has another repository where this pack is hosted.

**Comment by mcdodge34** [comment]
Why exactly is beyond my understanding, united forces are better than having 2 separate packs.

**Comment by Intipablo** [comment]
I agree a unified pack with both of our textures would be great.

**Comment by StefanTT** [comment]
It's not that easy, you cannot simply upload it somewhere, especially if there is an income from where you upload it. Further more F32Organization unfortunately has no license. That means it's proprietary and you must not upload it anywhere else. I am also not happy with the situation but I cannot change much here - I am also only a contributor with a little more rights. Besides that as I did much work for the textures as they are now I would not be happy if they are uploaded somewhere and somebody earns money from my work without my agreement.

**Comment by smenes** [comment]
unfortunately I don't have acces to F32.me. It was @DZCreeper 
@StefanTT you have all the perm now.

**Comment by StefanTT** [comment]
Thank you very much @smenes.

**Comment by DZCreeper** [comment]
I have updated the site, versions other than 1.12.2 won't be packaged from Github but can still be manually downloaded and updated.

Unless anyone has objections I would consider the license from the 1.7.10 version to still apply. Anyone can use, modify, or even distribute the pack. Generating profit from said distribution would be the only restricted item. I am largely unavailable to work on or even check my Github account these days so anyone who aims to improve the project with alternate hosting is welcome.

**Comment by StefanTT** [comment]
Thanks Alex.

How about using a creative commons license that matches best?
I think the Creative Commons BY-NC-SA license might fit well: 

https://creativecommons.org/licenses/by-nc-sa/4.0

**Comment by StefanTT** [comment]
Ok fine then I will add a proper license link and a license file to the repo.

**Comment by xMrVizzy** [comment]
Hey!

**Comment by StefanTT** [comment]
Great :-)
