### ISSUE TITLE
Mekanism Tools mod has Capital lettering

### ISSUE THREAD

**Issue by BentoGambin** [F32Organization/Faithful32-1.12.2#87]
How the names should be:
![image](https://user-images.githubusercontent.com/41645690/53922183-06609680-4052-11e9-8580-c28d93deabee.png)
How they currently are:
![image](https://user-images.githubusercontent.com/41645690/53922229-3dcf4300-4052-11e9-8eb2-d701d7cb8e6f.png)
The fix is very simple and i managed to do it automatically by using spacetornado renamer. Hope it helps and keep up the great work!

**Comment by StefanTT** [comment]
Thanks for the report, I did not notice yet - my current pack does not have mekanismtools installed. I will fix it soon.

**Comment by BentoGambin** [comment]
Nice!

**Comment by StefanTT** [comment]
Should be fixed now.
