### ISSUE TITLE
Biomes o plenty grass texture has issue I have fixed it!

### ISSUE THREAD

**Issue by CrackJackFlood** [F32Organization/Faithful32-1.12.2#99]
Go to to C:\Users\*Usernamehere*\AppData\Roaming\.minecraft\resourcepacks\Faithful32-1.12.2-master\assets\biomesoplenty\textures\blocks. Copy the 3 dirt textures loamy, sandy and silty to desktop. Rename them to grass_loamy_side, grass_sandy_side, grass_silty_side then copy them back to ^ that directory replace the broken textures and your done. :)

**Comment by CrackJackFlood** [comment]
Go to to C:\Users\*Usernamehere*\AppData\Roaming\.minecraft\resourcepacks\Faithful32-1.12.2-master\assets\biomesoplenty\textures\blocks. Copy the 3 dirt textures loamy, sandy and silty to desktop. Rename them to grass_loamy_side, grass_silty_side, grass_silty_side then copy them back to ^ that directory replace the broken textures and your done. :)
![unknown](https://user-images.githubusercontent.com/49882452/56778918-98725900-67d0-11e9-9d64-905bf21ddca5.png)
![unknown](https://user-images.githubusercontent.com/49882452/56778987-dbccc780-67d0-11e9-9fd0-ec9b09d97c0f.png)

**Comment by CrackJackFlood** [comment]
FIXED TEXTURES HERE


![grass_silty_side](https://user-images.githubusercontent.com/49882452/56779009-f56e0f00-67d0-11e9-80c3-5825b98895a3.png)
![grass_loamy_side](https://user-images.githubusercontent.com/49882452/56779010-f56e0f00-67d0-11e9-8399-98f02d5d3f7c.png)
![grass_sandy_side](https://user-images.githubusercontent.com/49882452/56779011-f56e0f00-67d0-11e9-8498-3b599dfa76c3.png)

**Comment by StefanTT** [comment]
Chances are that this leads to flickering for OpenGL renderers. I will have a look at it in a couple of hours and merge / adapt your fix.

**Comment by k-wins-it** [comment]
I just checked, and these textures are identical to the Vanilla 'grass_top' and 'grass_side_overlay' textures.
Therefore, the textures should be copied from 'Minecraft'.
I think this would also fix the issue

**Comment by CrackJackFlood** [comment]
> 
> 
> Chances are that this leads to flickering for OpenGL renderers. I will have a look at it in a couple of hours and merge / adapt your fix.

Just realised that the grass texture is a lower res to the rest of faithful there is your real bug
